cmd_drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.o := ../aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/gpu/arm/tMIx/b_r16p0/.mali_kbase_strings.o.d  -nostdinc -isystem /home/joshwiles/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9.x/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -Werror-implicit-function-declaration -Wno-format-security -Werror -std=gnu89 -fno-PIE -DANDROID_VERSION=990000 -mgeneral-regs-only -DCONFIG_AS_LSE=1 -fno-pic -fno-asynchronous-unwind-tables -fno-pic -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Os --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=2048 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Idrivers/gud/gud-exynos7885/MobiCoreDriver/mci/ -DMALI_CUSTOMER_RELEASE=1 -DMALI_USE_CSF=0 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r16p0-01rel0"\" -DMALI_KBASE_PLATFORM_PATH=../../drivers/gpu/arm/tMIx/b_r16p0/platform/"exynos" -I./drivers/staging/android -DMALI_KBASE_BUILD -Idrivers/gpu/arm/tMIx/b_r16p0 -Idrivers/gpu/arm/tMIx/b_r16p0/platform_dummy -Idrivers/gpu/arm/tMIx/b_r16p0/../../../base -I./include/linux -Idrivers/gpu/arm/tMIx/b_r16p0/backend/gpu -DMALI_CUSTOMER_RELEASE=1 -DMALI_USE_CSF=0 -DMALI_KERNEL_TEST_API=0 -DMALI_UNIT_TEST=0 -DMALI_COVERAGE=0 -DMALI_RELEASE_NAME=\""r16p0-01rel0"\" -DMALI_KBASE_PLATFORM_PATH=../../drivers/gpu/arm/tMIx/b_r16p0/platform/"exynos" -I./drivers/staging/android -DMALI_KBASE_BUILD -Idrivers/gpu/arm/tMIx/b_r16p0 -Idrivers/gpu/arm/tMIx/b_r16p0/platform_dummy -Idrivers/gpu/arm/tMIx/b_r16p0/../../../base -I./include/linux -Idrivers/gpu/arm/tMIx/b_r16p0 -Idrivers/gpu/arm/tMIx/b_r16p0/platform/exynos -Idrivers/gpu/arm/tMIx/b_r16p0/backend/gpu    -D"KBUILD_STR(s)=\#s" -D"KBUILD_BASENAME=KBUILD_STR(mali_kbase_strings)"  -D"KBUILD_MODNAME=KBUILD_STR(mali_kbase)" -c -o drivers/gpu/arm/tMIx/b_r16p0/.tmp_mali_kbase_strings.o drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.c

source_drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.o := drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.c

deps_drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.o := \
  drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.h \

drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.o: $(deps_drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.o)

$(deps_drivers/gpu/arm/tMIx/b_r16p0/mali_kbase_strings.o):
