# SPDX-License-Identifier: GPL-2.0
dtb-y += exynos7885.dtb
dtbo-y += exynos7904-gta3xlwifi_eur_open_03.dtbo
dtbo-y += exynos7904-gta3xlwifi_eur_open_04.dtbo

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
