cmd_drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.o := ../aarch64-linux-android-4.9/bin/aarch64-linux-android-gcc -Wp,-MD,drivers/media/platform/exynos/fimc-is2/.fimc-is-pipe.o.d  -nostdinc -isystem /home/joshwiles/projects/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9.x/include -I./arch/arm64/include -Iarch/arm64/include/generated/uapi -Iarch/arm64/include/generated  -Iinclude -I./arch/arm64/include/uapi -Iarch/arm64/include/generated/uapi -I./include/uapi -Iinclude/generated/uapi -include ./include/linux/kconfig.h -D__KERNEL__ -mlittle-endian -Wall -Wundef -Wstrict-prototypes -Wno-trigraphs -fno-strict-aliasing -fno-common -DANDROID_VERSION=990000 -mgeneral-regs-only -DCONFIG_AS_LSE=1 -fno-pic -fno-asynchronous-unwind-tables -fno-pic -fno-delete-null-pointer-checks -Wno-maybe-uninitialized -Os --param=allow-store-data-races=0 -DCC_HAVE_ASM_GOTO -Wframe-larger-than=4096 -fstack-protector-strong -Wno-unused-but-set-variable -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-var-tracking-assignments -g -Wdeclaration-after-statement -Wno-pointer-sign -fno-strict-overflow -fno-merge-all-constants -fmerge-constants -fno-stack-check -fconserve-stack -Werror=implicit-int -Werror=strict-prototypes -Werror=date-time -Idrivers/gud/gud-exynos7885/MobiCoreDriver/mci/ -Idrivers/media/platform/exynos/fimc-is2 -Idrivers/media/platform/exynos/fimc-is2/include -Idrivers/media/platform/exynos/fimc-is2/interface -Idrivers/media/platform/exynos/fimc-is2/hardware -Idrivers/media/platform/exynos/fimc-is2/hardware/api -Idrivers/media/platform/exynos/fimc-is2/vendor -Idrivers/media/platform/exynos/fimc-is2/sensor/csi -Idrivers/media/platform/exynos/fimc-is2/sensor/module_framework -Idrivers/media/platform/exynos/fimc-is2/vendor/mcd/preprocessor -Idrivers/media/platform/exynos/fimc-is2/ischain/fimc-is-v6_20_0 -Idrivers/media/platform/exynos/fimc-is2/vendor/mcd_v2    -D"KBUILD_STR(s)=$(pound)s" -D"KBUILD_BASENAME=KBUILD_STR(fimc_is_pipe)"  -D"KBUILD_MODNAME=KBUILD_STR(fimc_is)" -c -o drivers/media/platform/exynos/fimc-is2/.tmp_fimc-is-pipe.o drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.c

source_drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.o := drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.c

deps_drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.o := \

drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.o: $(deps_drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.o)

$(deps_drivers/media/platform/exynos/fimc-is2/fimc-is-pipe.o):
